<template>
  <div class="canvas">
    <a-navigation />
    <a-sidebar :links="links" />
    <main>
      <h1>Swish Privacy Policy</h1>
      <p>
        This Privacy Policy describes how Swish collects, uses and discloses information, and what choices you have with respect to the information. We respect the Browser's "Do Not Track" feature, you won't be affected by this policy if enabled.
      </p>
      <h3 id="1">
        Information We Collect
      </h3>
      <p>
        This website uses the web analysis service software Matomo (www.matomo.org), a service of the provider InnoCraft Ltd., 150 Willis St, 6011 Wellington, New Zealand, (“Matomo”) to collect and store data based on our legitimate interest in the statistical analysis of the user behavior for optimization and marketing purposes as per article 6(1) lit. f GDPR.
      </p>
      <p>
        This data can be used to create and evaluate pseudonymized usage profiles for the same purpose. For this purpose, cookies may be used. The data collected with the Matomo technology (including its pseudonymized IP address) is processed on servers, which are hosted by Contabo GmbH.
      </p>
      <p>
        Contabo GmbH does not have access to the servers nor the data that is processed (§ 6 Server-administration, Contabo's Terms & Conditions). For more information visit <a target="_blank" href="https://contabo.com/agb.html">Contabo's Terms & Conditions</a>.
      </p>
      <p>
        The information generated by the cookie in the pseudonymous user profile will not be used to personally identify the visitor to this website and will not be combined with personal data about the bearer of the pseudonym.
      </p>
      <h3 id="2">
        Proccessed Data
      </h3>
      <p>The following information is processed when visiting Swish:</p>
      <ul>
        <li>
          <strong>Cookie Information.</strong> Swish uses cookies on this website that are necessary for Matomo's analytics. The Websites and Services we provide, do not include cookies and similar tracking technologies of third parties. For more details about how we use these technologies, please see our <nuxt-link to="/cookie-policy">
            Cookie Policy
          </nuxt-link>.
        </li>
        <li>
          <strong>Log data.</strong> As with most websites and technology services delivered over the Internet, our servers automatically collect information when you access or use our Websites or Services and record it in log files. This log data may include the Internet Protocol (IP) address, the address of the web page visited before using the Website or Services, browser type and settings, the date and time the Services were used, information about browser configuration and plugins, language preferences and cookie data.
        </li>
        <li>
          <strong>Device information.</strong> Matomo collects information about devices accessing the Services, including type of device, what operating system is used, device settings, application IDs, unique device identifiers and crash data. Whether we collect some or all of this Other Information often depends on the type of device used and its settings.
        </li>
        <li>
          <strong>IP information.</strong> Your IP address will be pseudonymized by 2 byte(s) before any further processing of your data, e.g. 192.168.xxx.xxx.
        </li>
        <li>
          <strong>Location information.</strong> Matomo uses your pseudonymized IP address in order to approximate determine your location by country.
        </li>
      </ul>
      <h3 id="3">
        Data Retention
      </h3>
      <p>All data that is being processed, will be automatically deleted after 180 days.</p>
      <h3 id="4">
        How We Disclose and Share Information
      </h3>
      <p>
        The analytics for this project will not be shared with third parties at any given point. Long time contributors of the project may have access to view analytics interface while not being able to alter the data itself.
      </p>
      <h3 id="5">
        Opt Out From Tracking
      </h3>
      <p>
        If you do not agree to this data from your visit being stored and evaluated, then you can object to the storage and use at any time by clicking below. In this case, an opt-out cookie will be placed in your browser, which means that Matomo does not collect any session data. Please note that the complete deletion of your cookies means that the opt-out cookie will be deleted too and you may need to activate it again.
      </p>
      <a-cookie-frame />
      <h3 id="6">
        Contact Us
      </h3>
      <p>For any data privacy related enquiries, such as requesting a copy of your information or complete deletion, please contact us via mail at <a target="_top" href="mailto:swishidentity@gmail.com">swishidentity@gmail.com</a></p>
    </main>
    <a-footer />
  </div>
</template>

<script>
import CookieFrame from '@/components/CookieFrame'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import Sidebar from '@/components/Sidebar'

export default {
    components: {
        'a-cookie-frame': CookieFrame,
        'a-footer': Footer,
        'a-navigation': Navigation,
        'a-sidebar': Sidebar
    },

    data () {
        return {
            links: [
                {
                    id: 1,
                    title: 'Information We Collect'
                },
                {
                    id: 2,
                    title: 'Processed Data'
                },
                {
                    id: 3,
                    title: 'Data Retention'
                },
                {
                    id: 4,
                    title: 'How We Disclose and Share Information'
                },
                {
                    id: 5,
                    title: 'Opt Out From Tracking'
                },
                {
                    id: 6,
                    title: 'Contact Us'
                }
            ]
        }
    }
}
</script>

<style lang="sass" scoped>
@import '@/assets/styles/main'

.canvas
  line-height: 1.5
  letter-spacing: -0.03em

main
  padding: 80px 20px

  @include break-md
    padding: 80px 100px 80px 100px

  @include break-lg
    padding: 80px 100px 80px 450px

h1
  font-weight: fw(medium)
  color: color(font)

h3
  font-size: 18px
  font-weight: fw(medium)
  color: color(font)
  padding: 2rem 0 0

p
  color: color(font-lighten)
  font-size: 16px
  padding: 0.5rem 0

strong
  color: color(font)
  font-weight: fw(medium)

ul
  color: color(font-lighten)
  font-size: 16px
  line-height: 1.5
  padding: 0 0 0 2rem
  list-style: none

  li
    padding: 0.5rem 0
    position: relative

    &:before
      content: ""
      background: #c1c9d2
      width: 7px
      height: 7px
      border-radius: 50%
      position: absolute
      top: 0
      left: -20px
      top: 16px
      margin: auto
</style>
